/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Ad = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'rewardPoints' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const UpiWithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const RedemptionType = IDL.Variant({
  'cashout' : IDL.Null,
  'giftcard' : IDL.Null,
});
export const Redemption = IDL.Record({
  'id' : IDL.Nat,
  '_type' : RedemptionType,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const EarningsHistory = IDL.Record({
  'title' : IDL.Text,
  'adId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'points' : IDL.Nat,
});
export const Profile = IDL.Record({
  'username' : IDL.Text,
  'balance' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'redemptions' : IDL.Vec(Redemption),
  'adsWatched' : IDL.Nat,
  '_adsHistory' : IDL.Vec(EarningsHistory),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAd' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateAd' : IDL.Func([IDL.Nat], [], []),
  'getAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
  'getAllUpiWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(UpiWithdrawalRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getMyUpiWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(UpiWithdrawalRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemPoints' : IDL.Func([RedemptionType, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'submitUpiWithdrawal' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateAd' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateUpiWithdrawalStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'approved' : IDL.Null,
          'rejected' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'watchAd' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Ad = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'rewardPoints' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const UpiWithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const RedemptionType = IDL.Variant({
    'cashout' : IDL.Null,
    'giftcard' : IDL.Null,
  });
  const Redemption = IDL.Record({
    'id' : IDL.Nat,
    '_type' : RedemptionType,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const EarningsHistory = IDL.Record({
    'title' : IDL.Text,
    'adId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'points' : IDL.Nat,
  });
  const Profile = IDL.Record({
    'username' : IDL.Text,
    'balance' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'redemptions' : IDL.Vec(Redemption),
    'adsWatched' : IDL.Nat,
    '_adsHistory' : IDL.Vec(EarningsHistory),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAd' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateAd' : IDL.Func([IDL.Nat], [], []),
    'getAds' : IDL.Func([], [IDL.Vec(Ad)], ['query']),
    'getAllUpiWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(UpiWithdrawalRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getMyUpiWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(UpiWithdrawalRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemPoints' : IDL.Func([RedemptionType, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'submitUpiWithdrawal' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateAd' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateUpiWithdrawalStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'approved' : IDL.Null,
            'rejected' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'watchAd' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };