/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ad {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'rewardPoints' : bigint,
  'description' : string,
  'isActive' : boolean,
  'category' : string,
  'videoUrl' : [] | [string],
}
export interface EarningsHistory {
  'title' : string,
  'adId' : bigint,
  'timestamp' : bigint,
  'points' : bigint,
}
export interface Profile {
  'username' : string,
  'balance' : bigint,
  'totalPoints' : bigint,
  'redemptions' : Array<Redemption>,
  'adsWatched' : bigint,
  '_adsHistory' : Array<EarningsHistory>,
}
export interface Redemption {
  'id' : bigint,
  '_type' : RedemptionType,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type RedemptionType = { 'cashout' : null } |
  { 'giftcard' : null };
export interface UpiWithdrawalRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'userId' : Principal,
  'timestamp' : bigint,
  'upiId' : string,
  'amount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAd' : ActorMethod<
    [string, string, bigint, bigint, string, [] | [string]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateAd' : ActorMethod<[bigint], undefined>,
  'getAds' : ActorMethod<[], Array<Ad>>,
  'getAllUpiWithdrawals' : ActorMethod<[], Array<UpiWithdrawalRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<Profile>>,
  'getMyUpiWithdrawals' : ActorMethod<[], Array<UpiWithdrawalRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemPoints' : ActorMethod<[RedemptionType, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'submitUpiWithdrawal' : ActorMethod<[string, bigint], undefined>,
  'updateAd' : ActorMethod<
    [bigint, string, string, bigint, bigint, string, [] | [string]],
    undefined
  >,
  'updateUpiWithdrawalStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'approved' : null } |
        { 'rejected' : null },
    ],
    undefined
  >,
  'watchAd' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];